export const ITEM_REQUEST_INITIATED = "ITEM_REQUEST_INITIATED";
export const ITEM_REQUEST_SUCCESS = "ITEM_REQUEST_SUCCESS";
export const ITEM_REQUEST_FAILED = "ITEM_REQUEST_FAILED";

export const CATEGORY_REQUEST_INITIATED = "CATEGORY_REQUEST_INITIATED";
export const CATEGORY_REQUEST_SUCCESS = "CATEGORY_REQUEST_SUCCESS";
export const CATEGORY_REQUEST_FAILED = "CATEGORY_REQUEST_FAILED";

export const CART_REQUEST_INITIATED = "CART_REQUEST_INITIATED";
export const CART_REQUEST_SUCCESS = "CART_REQUEST_SUCCESS";
export const CART_REQUEST_FAILED = "CART_REQUEST_FAILED";

export const CARTITEM_REQUEST_INITIATED = "CARTITEM_REQUEST_INITIATED";
export const CARTITEM_REQUEST_SUCCESS = "CARTITEM_REQUEST_SUCCESS";
export const CARTITEM_REQUEST_FAILED = "CARTITEM_REQUEST_FAILED";
export const CARTITEM_CREATE_SUCCESS = "CARTITEM_CREATE_SUCCESS";
export const CARTITEM_DELETE_SUCCESS = "CARTITEM_DELETE_SUCCESS";
export const CARTITEM_UPDATE_SUCCESS = "CARTITEM_UPDATE_SUCCESS";
export const MERGE_CARTITEMS = "MERGE_CARTITEMS";
// export const CREATE_CARTITEM_

export const FETCH_AUTHORISATION_REQUEST = "FETCH_AUTHORISATION_REQUEST";
export const FETCH_AUTHORISATION_SUCCESS = "FETCH_AUTHORISATION_SUCCESS";
export const FETCH_AUTHORISATION_ERROR = "FETCH_AUTHORISATION_ERROR";
export const FETCH_STORED_TOKEN = "FETCH_STORED_TOKEN";

export const ORDER_REQUEST_INITIATED = "ORDER_REQUEST_INITIATED";
export const ORDER_REQUEST_SUCCESS = "ORDER_REQUEST_SUCCESS";
export const ORDER_REQUEST_FAILED = "ORDER_REQUEST_FAILED";
export const ORDER_CREATE_REQUEST_SUCCESS = "ORDER_CREATE_REQUEST_SUCCESS";
export const ORDER_UPDATE = "ORDER_UPDATE"

export const ADDRESS_REQUEST_INITIATED = "ADDRESS_REQUEST_INITIATED";
export const ADDRESS_REQUEST_SUCCESS = "ADDRESS_REQUEST_SUCCESS";
export const ADDRESS_REQUEST_FAILED = "ADDRESS_REQUEST_FAILED";

export const PACKAGE_REQUEST_INITIATED = "PACKAGE_REQUEST_INITIATED";
export const PACKAGE_REQUEST_SUCCESS = "PACKAGE_REQUEST_SUCCESS";
export const PACKAGE_REQUEST_FAILED = "PACKAGE_REQUEST_FAILED";

export const LOCATION_REQUEST_INITIATED = "LOCATION_REQUEST_INITIATED";
export const LOCATION_REQUEST_SUCCESS = "LOCATION_REQUEST_SUCCESS";
export const LOCATION_REQUEST_FAILED = "LOCATION_REQUEST_FAILED";
export const PLACE_REQUEST_INITIATED = "PLACE_REQUEST_INITIATED";
export const PLACE_REQUEST_SUCCESS = "PLACE_REQUEST_SUCCESS";
export const PLACE_REQUEST_FAILED = "PLACE_REQUEST_FAILED";

export const APPOINTMENT_REQUEST_INITIATED = "APPOINTMENT_REQUEST_INITIATED";
export const APPOINTMENT_REQUEST_SUCCESS = "APPOINTMENT_REQUEST_SUCCESS";
export const APPOINTMENT_REQUEST_FAILED = "APPOINTMENT_REQUEST_FAILED";
export const APPOINTMENT_LOCAL_UPDATE = "APPOINTMENT_LOCAL_UPDATE"

export const VALIDATION_INITIATED = "VALIDATION_INITIATED"
export const VALIDATION_SUCCESS = "VALIDATION_SUCCESS"
export const SIGN_OUT = "SIGN_OUT"
export const VALIDATION_FAILED = "VALIDATION_FAILED"
export const ON_LOGIN_INITIATED = "ON_LOGIN_INITIATED"
export const ON_LOGIN_SUCCESS = "ON_LOGIN_SUCCESS"
export const ON_LOGIN_FAILED = "ON_LOGIN_SUCCESS"
export const ON_REQUEST_LOGIN = "ON_REQUEST_LOGIN";
export const ON_REQUEST_LOGIN_CANCEL = "ON_REQUEST_LOGIN_CANCEL";

export const USER_REQUEST_INITIATED = "USER_REQUEST_INITIATED";
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_FAILED = "USER_REQUEST_FAILED";
export const USER_DETAILS_UPDATED = "USER_DETAILS_UPDATED";

export const SESSION_AUTHENTICATING = "SESSION_AUTHENTICATING"
export const SESSION_AUTHENTICATED = "SESSION_AUTHENTICATED"
export const SESSION_AUTHENTICATION_FAILED = "SESSION_AUTHENTICATION_FAILED"
export const SESSION_UNAUTHENTICATING = "SESSION_UNAUTHENTICATING"
export const SESSION_UNAUTHENTICATED = "SESSION_UNAUTHENTICATED"
export const SESSION_UNAUTHENTICATION_FAILED = "SESSION_UNAUTHENTICATION_FAILED"

export const NETWORK_AVAIABLE = "NETWORK_AVAIABLE"
export const NETWORK_UNAVAIABLE = "NETWORK_UNAVAIABLE"

export const REWARD_REQUEST_INITIATED = "REWARD_REQUEST_INITIATED"
export const REWARD_REQUEST_SUCCEED = "REWARD_REQUEST_SUCCEED"
export const REWARD_REQUEST_FAILED = "REWARD_REQUEST_FAILED"

export const REFERRAL_REQUEST_INITIATED = "REFERRAL_REQUEST_INITIATED"
export const REFERRAL_REQUEST_SUCCEED = "REFERRAL_REQUEST_SUCCEED"
export const REFERRAL_REQUEST_FAILED = "REFERRAL_REQUEST_FAILED"